### ISSUE TITLE
Settings are no longer working

### ISSUE THREAD

**Issue by miyconst** [Starcounter/PlaygroundKeeper#4]
After the latest changes the settings section of PlaygroundKeeper is no longer working.

Trying to make a change results in the following error:

```
"System.Exception: ScErrAcquireSessionTimeout (SCERR5008): Exclusive access to the session could not be obtained.
Version: 2.2.1852.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR5008.
   at Starcounter.Session.StartUsing() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 528
   at Starcounter.Session.Use(SessionTask action, String sessionId) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 710
   at Starcounter.Session.ScheduleTask(String sessionId, SessionTask task, Boolean waitForCompletion) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 287
   at Starcounter.Session.ScheduleTask(IEnumerable`1 sessionIds, SessionTask task, Boolean waitForCompletion) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 336
   at Administrator.Server.Model.Server.OnChanged(Object sender, EventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.Administrator\Server\Model\Server.cs:line 196
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at Administrator.Server.Model.Server.InvalidateDatabases() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.Administrator\Server\Model\Server.cs:line 244
   at Administrator.Server.Managers.ServerManager.<>c.<RegisterInternalModelApi>b__9_1(String databaseName, Request request) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 294
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-285\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR5008
"
```

**Comment by andwah** [comment]
Maybe this is related https://github.com/Starcounter/Starcounter/issues/3522

**Comment by chrhol** [comment]
> Maybe this is related Starcounter/Starcounter#3522

That's my guess as well. I'm looking into the other issue now.

**Comment by miyconst** [comment]
I don't think so, should be investigated.

**Comment by miyconst** [comment]
Actually, I be wrong, it might be related.

**Comment by andwah** [comment]
I think this is resolved and fixed in the `ScheduleTask` handling.

@miyconst  Can this be closed?

**Comment by miyconst** [comment]
Yes, I think so.
